turtlebot:
  arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - arm_shoulder_pan_joint
      - arm_bicep_joint
      - arm_forearm_joint
      - arm_wrist_flex_joint
      - gripper_link_joint
    gains:
      arm_shoulder_pan_joint: {p: 2.5, i: 0.0, d: 0.05}
      arm_bicep_joint: {p: 2.5, i: 0.0, d: 0.05}
      arm_forearm_joint: {p: 2.5, i: 0.0, d: 0.05}
      arm_wrist_flex_joint: {p: 2.5, i: 0.0, d: 0.05}
      gripper_link_joint: {p: 2.5, i: 0.0, d: 0.05}
  gripper_controller:
    # Unfortunately this controller type works only for grippers with a single joint :( 
    #type: "effort_controllers/GripperActionController"
    type: "effort_controllers/JointTrajectoryController"
    joints: 
      - gripper_joint
      - gripper2_joint
    gains: 
      gripper_joint: {p: 2.5, i: 0.0, d: 0.05}
      gripper2_joint: {p: 2.5, i: 0.0, d: 0.05}

#---------------------------------version 2 ---------------------------------
#   Publish all joint states -----------------------------------
#  joint_state_controller:
#    type: joint_state_controller/JointStateController
#    publish_rate: 50  
#   Position Controllers ---------------------------------------
#  arm_shoulder_pan_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: arm_shoulder_pan_joint
#    pid: {p: 32.0, i: 0.01, d: 0.0}
#  arm_shoulder_lift_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: arm_bicep_joint
#    pid: {p: 32.0, i: 0.01, d: 0.0}
#  arm_elbow_flex_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: arm_forearm_joint
#    pid: {p: 32.0, i: 0.01, d: 0.0}
#  arm_wrist_flex_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: arm_wrist_flex_joint
#    pid: {p: 32.0, i: 0.01, d: 0.0}
#  arm_gripper_controller:
#    type: effort_controllers/JointPositionController
#    joint: gripper_link_joint
#    pid: {p: 32.0, i: 0.01, d: 0.0}
